### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by golovanov** [yiisoft/yii2-httpclient#10]
I disagree with the name of the classes TransportCulr, TransportStream, ParserJson, FormatterJson, etc.
Other classes in Yii in general have the next name format - \<Type\>  or \<\<Subtype\>Type\>

Example:
- Validator, EmailValidator, StringValidator, SafeValidator, ...
- Session, CacheSession, DbSession, ...
- Action, ErrorAction, CaptchaAction, ...
- Exception, ConflictHttpException, ForbiddenHttpException, ...
- ...

I suggest to change the next classes to general name format:
- FormatterJson => JsonFormatter
- FormatterUrlEncoded => UrlEncodedFormatter
- FormatterXml => XmlFormatter
- ParserJson => JsonParser
- ParserXml => XmlParser
- ParserUrlEncoded => UrlEncodedParser
- TransportCurl => CurlTransport
- TransportStream => StreamTransport

**Comment by samdark** [comment]
Makes sense.

**Comment by klimov-paul** [comment]
Resolved by commit 1e2f4fb
