### ISSUE TITLE
Invalid cookie validation

### ISSUE THREAD

**Issue by yugene** [yiisoft/yii2-httpclient#101]
### What steps will reproduce the problem?
Try to send a request with any valid cookie (e.g session_id).

### What's expected?
Request with valid cookie sent is expected.

### What do you get instead?
Request fails with 'Cookie name ... is invalid'

### Additional info
This relates to issue #98. You have test for cookie validation function and this function is correct. But you do use it's result incorrectly. Request.php:482 and Request.php:485 should only throw an exception when cookie IS NOT VALID, while now it is thrown when cookie IS VALID.

| Q                       | A
| ----------------------- | ---
| Yii HTTP Client version | 2.0.4 |

**Comment by klimov-paul** [comment]
Resolved by commit 677ab88f633b5c26a217380839c70f598bb69bc1
Thank yu for the report.
