### ISSUE TITLE
The requested package yiisoft/yii2-httpclient could not be found in any version

### ISSUE THREAD

**Issue by heyuanchao** [yiisoft/yii2-httpclient#11]
E:\xampp\htdocs\html5\php\yii-advanced-app-2.0.6>composer require --prefer-dist yiisoft/yii2-httpclient "*"
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package yiisoft/yii2-httpclient could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by samdark** [comment]
That's correct. There were no releases of it yet.
