### ISSUE TITLE
Proxy auth settings not working

### ISSUE THREAD

**Issue by SoleSS** [yiisoft/yii2-httpclient#110]
$client = new Client();
        $response = $client->createRequest()
                        ->setMethod('post')
			->setUrl('https://2ip.ru')
                        ->setData($params);

	    $response = $response->setOptions([
		CURLOPT_PROXYTYPE => 'SOCKS5', // tryed 'HTTP'\'HTTPS'\CURLPROXY_SOCKS5 as well
		CURLOPT_PROXY => $proxy['proxy_host'],
		CURLOPT_PROXYPORT => $proxy['proxy_port'],
		CURLOPT_PROXYUSERPWD => $proxy['proxy_login'].':'.$proxy['proxy_password'],
	    ]);

request is sent, but in logs (local testing) and in output of 2ip.ru IP is not changed ...

**Comment by rob006** [comment]
Curl is not a default transport - you need to specify transport class directly in this case: https://github.com/yiisoft/yii2-httpclient/blob/a28a87407d4b23628b07c4e5c992278c3b867611/docs/guide/usage-request-options.md

```php
$client = new Client([
    'transport' => 'yii\httpclient\CurlTransport' // only cURL supports the options we need
]);
```

**Comment by SoleSS** [comment]
Many thanks +1:
