### ISSUE TITLE
Add header doesn`t work

### ISSUE THREAD

**Issue by e1sep0** [yiisoft/yii2-httpclient#113]
$result = $this->client->createRequest()
            ->setMethod($method)
            ->setFormat(Client::FORMAT_JSON)
            ->setUrl($url)
            ->setData($options);

        if ($token) {
            $result->addHeaders(["token" => "token"]);
        }

$result->send();

$result->getHeaders() - show this header
But answer from server is wrong - doesn`t have token

**Comment by cebe** [comment]
> But answer from server is wrong - doesn`t have token

what does that mean? which token?

**Comment by e1sep0** [comment]
I need token to pass authorization. In POSTMAN i get result: http://joxi.ru/EA4pRk3fw6a08A
But when i try to use it in Yii2, i get Error: Sender:  Authorization failed.

**Comment by e1sep0** [comment]
CURL works with same params:
curl_setopt_array($curl, array(
            CURLOPT_URL => "https://api-ka_agregator.amber-saas.com/API/V1.svc/executeQuery",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => json_encode($options),
            CURLOPT_HTTPHEADER => array(
                "content-type: application/json",
                "token: ".$token
            ),
        ));

**Comment by samdark** [comment]
If CURL works then there's something wrong with another client and it can't be fixed withing the framework.
