### ISSUE TITLE
Cookie value validation restrictions

### ISSUE THREAD

**Issue by Standoffru** [yiisoft/yii2-httpclient#114]
Consider the following cookie with value: 112=DOt6eREIidq3Wy.
I got InvalidConfigException because the value can not contain ("=") character.
In this source https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie cookie value can contain ("=").
Quote: A <cookie-value> can optionally be set in double quotes and any US-ASCII characters excluding CTLs, whitespace, double quotes, comma, semicolon, and backslash are allowed.

**Comment by klimov-paul** [comment]
Unable to reproduce. Value with `=` use case is covered by unit tests:
https://github.com/yiisoft/yii2-httpclient/blob/master/tests/RequestTest.php#L385

**Comment by MaXL-ru** [comment]
@klimov-paul It's a bug. Cookie value may contain "=" symbol.

> A <cookie-value> can optionally be set in double quotes and any US-ASCII characters excluding CTLs, whitespace, double quotes, comma, semicolon, and backslash are allowed. Encoding: Many implementations perform URL encoding on cookie values, however it is not required per the RFC specification. It does help satisfying the requirements about which characters are allowed for <cookie-value> though.

**Comment by klimov-paul** [comment]
I am unable to reproduce the issue - library allows `=` symbol at cookie value.
If you are able to reproduce the issue - specify a unit test for it.

**Comment by samdark** [comment]
Should be because of comma, not because of `=`. `=` is allowed according to the document you've quoted. @klimov-paul could you check about `.`?

**Comment by Standoffru** [comment]
Sorry. I did not check the commit a0b5ff6e61fbb73cef7f7f7f59ace1c144db550a
