### ISSUE TITLE
Request::composeHeaderLines() capitalizes header names

### ISSUE THREAD

**Issue by dvanderh** [yiisoft/yii2-httpclient#116]
### What steps will reproduce the problem?
Adding headers like this:
`            ->addHeaders([
                'Accept' => 'application/json',
                'content-type' => 'application/json',
                'api_key' => $this->getApiKey(),
                'locale' => $this->getLocale(),
            ])`
### What's expected?
`
Headers like this, exactly what I submitted:
[0]=>
--
  | string(24) "Accept: application/json"
  | [1]=>
  | string(30) "content-type: application/json"
  | [2]=>
  | string(49) "api_key: 959cd3cc3790f8007725938c410b92ccd9a993b2"
  | [3]=>
  | string(10) "locale: nl"

`
### What do you get instead?
`

[0]=>
--
  | string(24) "Accept: application/json"
  | [1]=>
  | string(30) "Content-Type: application/json"
  | [2]=>
  | string(49) "Api_key: 959cd3cc3790f8007725938c410b92ccd9a993b2"
  | [3]=>
  | string(10) "Locale: nl"

`

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii HTTP Client version |
| PHP version             |
| Operating system        |

**Comment by klimov-paul** [comment]
Whould not be fixed.
Header names are case-insensitive, so it does not matter.

**Comment by dvanderh** [comment]
It does though, the api I'm using this with does not accept the upper case names. Without the ucwords in Message::composeHeaderLines() it works.

**Comment by klimov-paul** [comment]
According to RFC 2616 specification header names are case-insensitive:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

If your API violates RFC - it should be fixed there.

**Comment by nkostadinov** [comment]
@klimov-paul  I have the exactly same problem here. It doesnt matter what is the RFC if some APIs do not respect it. That's not the way to solve the problem, I think we should be able to modify easily this functionality.

The Yii framework itself has a lot of cases where it bends for something that doesn't follow the RFC e.g. Internet explorer. But the solution is not to call microsoft to fix their browser.

**Comment by ExploHash** [comment]
@klimov-paul If the RFC says it's case-insensitive, why is it capatalized than?
