### ISSUE TITLE
Cookie name and value validation is too strict

### ISSUE THREAD

**Issue by pawelkania** [yiisoft/yii2-httpclient#118]
This is more suggestion than an issue.
yiisoft/yii2-httpclient is often used as website crawler, many websites are using invalid cookie names like `some/name` - this name is not valid according to RFC6265 (RFC2616) but I think validation should allow slash(and possible other characters) in names because to strict validation make `setCookie()` useless for website crawling. There is similar problem with cookie value.

**Comment by bscheshirwork** [comment]
May be made of this validation as optional 
like
`useStrict` / `useWeak`

**Comment by klimov-paul** [comment]
Resolved by commit 2b361b5f7fac31c96517438b8e9c9b12e3bcaba4
