### ISSUE TITLE
`Request` lost `batchSend`

### ISSUE THREAD

**Issue by leaf-fly** [yiisoft/yii2-httpclient#12]
I want to use `curl_multi` but request without `batchSend` call.
Failed to find any guidance.
How to do this?

**Comment by klimov-paul** [comment]
What is the sense of using `curl_multi` for the single request?

**Comment by leaf-fly** [comment]
Not a single request.
When to collect multiple sites content at the same time.
Common method is `curl_multi`.How to use `curl_multi` method from `httpclient`.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-httpclient/blob/master/Client.php#L221

**Comment by klimov-paul** [comment]
Issue resolved by commit 6574668
