### ISSUE TITLE
Test with server php.net not us.php.net

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-httpclient#122]
I have error in test `\yiiunit\extensions\httpclient\StreamTransportTest::testFollowLocation` 80-90% times
```sh
fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```
also I can see same situation on [Pull Requests - Build #117 - Job #117.4](https://travis-ci.org/yiisoft/yii2-httpclient/jobs/286577173)
```sh
There were 2 errors:

1) yiiunit\extensions\httpclient\CurlTransportTest::testFollowLocation

yii\httpclient\Exception: Curl error: #6 - Could not resolve host: us1.php.net


2) yiiunit\extensions\httpclient\StreamTransportTest::testFollowLocation

yii\httpclient\Exception: fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

I have no error with `http://php.net`

Why         
```php
$client->baseUrl = 'http://us.php.net';
```
not
```php
$client->baseUrl = 'http://php.net';
```
?
https://github.com/yiisoft/yii2-httpclient/blob/4f82ef36021af046ddd3ccb857b334af8e596c79/tests/TransportTestCase.php#L99

Trevis servers closest to 'http://us.php.net' not near of 'http://php.net'?

### What steps will reproduce the problem?
run tests

### What's expected?
all tests is ok

### What do you get instead?
https://travis-ci.org/yiisoft/yii2-httpclient/jobs/286577173

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | dev
| Yii HTTP Client version | dev
| PHP version             | 7.1.10
| Operating system        | debian

**Comment by klimov-paul** [comment]
Resolved by commit b152886ea15ffa70de1ff055d99e6e4ef04868b1
