### ISSUE TITLE
Travis HHVM fail on \Exception

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-httpclient#125]
### What steps will reproduce the problem?
see [Build #119  - Job #119.6](https://travis-ci.org/yiisoft/yii2-httpclient/jobs/286958512)

### What's expected?
test pass / not support HHVM / change code ?

```php
            throw new Exception($e->getMessage(), $e->getCode(), $e);
```
so.. in HHVM the realization of `\Exception` is different? or `$e->getMessage()`, `$e->getCode()` is different?

### What do you get instead?
```sh
PHPUnit 5.7.22 by Sebastian Bergmann and contributors.
Runtime:       HHVM 3.18.5
Configuration: /home/travis/build/yiisoft/yii2-httpclient/phpunit.xml.dist

...............................................................  63 / 116 ( 54%)
.............................S..E....................           116 / 116 (100%)

Time: 9.81 seconds, Memory: 30.65MB
There was 1 error:
1) yiiunit\extensions\httpclient\StreamTransportTest::testSendPost
yii\httpclient\Exception: Array to string conversion
/home/travis/build/yiisoft/yii2-httpclient/StreamTransport.php:68
/home/travis/build/yiisoft/yii2-httpclient/Client.php:221
/home/travis/build/yiisoft/yii2-httpclient/Request.php:422
/home/travis/build/yiisoft/yii2-httpclient/tests/TransportTestCase.php:59
/home/travis/build/yiisoft/yii2-httpclient/vendor/phpunit/phpunit/phpunit:52
```

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | dev
| Yii HTTP Client version | dev
| PHP version             | HHVM 3.18.5
| Operating system        | trevis

**Comment by klimov-paul** [comment]
> in HHVM the realization of \Exception is different? or $e->getMessage(), $e->getCode() is different?

It has nothing to do with exceptions. According to the stacktrace there is some problem around `fopen()` invocation:
https://github.com/yiisoft/yii2-httpclient/blob/master/StreamTransport.php#L61

**Comment by klimov-paul** [comment]
I am closing this issue since I have no way to solve it.
Besides supporting HHVM, which is already abandoned by its author, is not the priority.

**Comment by bscheshirwork** [comment]
> According to the stacktrace there is some problem around fopen() invocation

and this "problem around fopen()" rise \Exception $e with array in "field" message and/or code?

So... we can remove HHVM from Travis?
