### ISSUE TITLE
Either fix 5.4 tests or set 5.5 as requirement

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-httpclient#126]
See https://github.com/yiisoft/yii2-httpclient/commit/e61daa63eca37f21daca1f9f79888ffa3ba5836d

**Comment by klimov-paul** [comment]
> Either fix 5.4 tests or set 5.5 as requirement

I don't get it: do you have any indication that library can not funtion at PHP 5.4 anymore?
Which particular part causing trouble then?

**Comment by samdark** [comment]
We don't have a proof it can. That's the problem.

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/issues/14973

**Comment by klimov-paul** [comment]
Resolved by commit 548b503b3666144016bf3730b9b54ce9af2a0d9c
