### ISSUE TITLE
curl request method

### ISSUE THREAD

**Issue by 4meck** [yiisoft/yii2-httpclient#130]
### What steps will reproduce the problem?
$client = new \yii\httpclient\Client([
    'transport' => 'yii\httpclient\CurlTransport',
]);
$request = $client->createRequest()
->setOptions([
    CURLOPT_CUSTOMREQUEST	=> 'NLST',
....
]);
echo $request->getMethod();  # = get

### What do you get instead?
https://github.com/yiisoft/yii2-httpclient/blob/master/CurlTransport.php#L147
(-) $curlOptions[CURLOPT_CUSTOMREQUEST] = $method;
(+) if (empty($curlOptions[CURLOPT_CUSTOMREQUEST]))
$curlOptions[CURLOPT_CUSTOMREQUEST] = $method;

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |  2.0.14-dev
| Yii HTTP Client version |  2.0.6
| PHP version             | 7.1
| Operating system        |

**Comment by klimov-paul** [comment]
Use `Request::setMethod()` instead,
