### ISSUE TITLE
Max timeout is 120s

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii2-httpclient#131]
### What steps will reproduce the problem?
```php
$client = new Client([
     'baseUrl' => Yii::$app->params['baseUrl'],
     'transport' => 'yii\httpclient\CurlTransport',
]);
$request = $client->get($method . '/data/', $params, [], [
     'timeout' => 300,
]);

try{
     $s = time();
     $request->send();
}catch (\Exception $exception){
     echo (int)(time() - $s);
     exit();
}
```
### What's expected?
~300s
### What do you get instead?
~120s

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.14-dev
| Yii HTTP Client version | last
| PHP version             | 7.0.22
| Operating system        | Ubuntu 16

**Comment by xepozz** [comment]
PHP max execution time is 300s

**Comment by klimov-paul** [comment]
Unable to reproduce.

**Comment by xepozz** [comment]
ok try once more

**Comment by xepozz** [comment]
@klimov-paul try it again

**Comment by klimov-paul** [comment]
Answer me the following question if you set `timeout` to be equal to 2 seconds, you still ending in 120 seconds script running?
