### ISSUE TITLE
http request should support curl as well in case of fopen is disabled

### ISSUE THREAD

**Issue by thehiddennepali** [yiisoft/yii2-httpclient#132]

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-httpclient/blob/master/docs/guide/usage-transports.md

**Comment by thehiddennepali** [comment]
I am using yii\authclient\clients\Facebook this and I am using configuration as 
`'components' => [
    'authClientCollection' => [
        'class' => 'yii\authclient\Collection',
        'clients' => [
            'facebook' => [
                'class' => 'yii\authclient\clients\Facebook',
                'clientId' => 'facebook_client_id',
                'clientSecret' => 'facebook_client_secret',
            ],
        ],
    ]
    // ...
]`

and in View i used as
`<?= yii\authclient\widgets\AuthChoice::widget([
     'baseAuthUrl' => ['site/auth'],
	'popupMode' => false,

]) ?>`

so where do i need to set the transport so that i can tell that the facebook authclient uses the CurlTransport

**Comment by cebe** [comment]
You can configure the `httpClient` property of the `facebook` client:

```php
'httpClient' => [
    'class' => 'yii\httpclient\Client',
    'transport' => 'yii\httpclient\CurlTransport',
]

```
