### ISSUE TITLE
Support multiple files under the same field name

### ISSUE THREAD

**Issue by softbread** [yiisoft/yii2-httpclient#134]
### What steps will reproduce the problem?
I want to emulate a file input field which could support multiple file selection. So I have to pass files to 'txt' field twice like this:
```php
$client ->addFile('txt', 'test1.txt')
            ->addFile('txt', 'test2.txt');
```

### What's expected?
I would expect the two files will be added under the same parameter 'txt'.
### What do you get instead?
I only get 'test2.txt' as the later one will always override the previous values.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.13
| Yii HTTP Client version | 2.0.5
| PHP version             | 7.1.11

**Comment by klimov-paul** [comment]
Rejected.
You should control the actual input name including brackets (`[]`) and index on your own.
`Request` is unable to so this for you since, in case only one file with some name (e.g. 'someFile') is attached, it is unknown where it should be send with input name 'someFile' or 'someFile[]'.
