### ISSUE TITLE
character encoding problem cause by commit d2849ad

### ISSUE THREAD

**Issue by qwerty199369** [yiisoft/yii2-httpclient#135]
![image](https://user-images.githubusercontent.com/32596673/35266496-6f3abde6-005e-11e8-9d8a-aae3518c3cea.png)

character encoding problem cause by commit https://github.com/yiisoft/yii2-httpclient/commit/d2849adfa4d05acb94ebb95bae41b55b0318def2

**Comment by klimov-paul** [comment]
Resolved by commit 9ef0dbd
