### ISSUE TITLE
Scrutinizer integration is broken

### ISSUE THREAD

**Issue by zhukovra** [yiisoft/yii2-httpclient#141]
### What steps will reproduce the problem?
Run build in Travic CI. [Example](https://travis-ci.org/yiisoft/yii2-httpclient/jobs/333234927)

### What's expected?
Code coverage data is generated and uploaded to [scrutinizer-ci.com](https://scrutinizer-ci.com)

### What do you get instead?
Error on generation coverage:
![image](https://user-images.githubusercontent.com/289431/35575552-b87f14e0-05ed-11e8-9843-cf8363648c3c.png)

Error on upload coverage data:
![image](https://user-images.githubusercontent.com/289431/35575137-b364f0b6-05ec-11e8-9053-9494e275da04.png)

**Comment by klimov-paul** [comment]
Scrutinizer integration can not be broken as it has never been integrated.
Obsolete Travis code removed.
