### ISSUE TITLE
Option followLocation not working

### ISSUE THREAD

**Issue by scryba** [yiisoft/yii2-httpclient#150]
$client = new Client();
                        $response = $client->createRequest()
                            ->setMethod('post')
                            ->setUrl("https://example.org/")
                            ->setData([
                                'rt' => 67,
                           
                            ])
                            ->setOptions([
                                'followLocation' => true,
                              
                            ])
                            ->send();

| Q                       | A
| ----------------------- | ---
| Yii version            | = 2.0.15.1 
| Yii HTTP Client version  | = 2.0.6 
| PHP version          | = 7.2.5   
| Operating system        | = Ubuntu 16.04

**Comment by cebe** [comment]
what do you expect `followLocation` to do on a POST request? behavior would be well defined on GET but its not clear how it should work on POST request.

**Comment by samdark** [comment]
Closing since there was no response for a long time.
