### ISSUE TITLE
> yii\base\UnknownMethodException: Calling unknown method: yii\console\Application::getSession()

### ISSUE THREAD

**Issue by thyseus** [yiisoft/yii2-httpclient#154]
### What steps will reproduce the problem?

1: Push a Job that uses yii2-httpclient on to a Queue:

```php
   Yii::$app->queue->push(new LicenseJob([
                                'strategy_id' => $strategy->id,
                                'user_id' => $download->user_id,
                                'download_id' => $download->id,
                                'domain' => $download->domain,
                            ]));
```

2: Execute the Worker:

 php yii queue/run --verbose --color

### What's expected?

Job should run without problems

### What do you get instead?

2018-05-22 18:53:35 [pid: 30575] - Worker is started
2018-05-22 18:53:35 [45] app\jobs\LicenseJob (attempt: 1, pid: 30575) - Started
2018-05-22 18:53:35 [45] app\jobs\LicenseJob (attempt: 1, pid: 30575) - Error (0.294 s)
> yii\base\UnknownMethodException: Calling unknown method: yii\console\Application::getSession()
2018-05-22 18:53:35 [pid: 30575] - Worker is stopped (0:00:00)

### Additional info
I also tried to set 'session' to config/console.php but without success.

Is it possible to use yii2-httpclient from a console application or do i need to fall back to plain curl?

Thanks a lot !

**Comment by samdark** [comment]
Do you have a stacktrace for the error? I see no reason why httpclient would try access session by itself...
