### ISSUE TITLE
fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F119:SSL routines:func(143):reason(281)

### ISSUE THREAD

**Issue by netscorpion** [yiisoft/yii2-httpclient#155]
### What steps will reproduce the problem?
StreamTransport.php

### What's expected?

Receiving a response from RestAPI

### What do you get instead?

fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F119:SSL routines:func(143):reason(281)

I write in Russian because it's easier to set out the problem. Ready to describe problem in English.

Прошу прощения за обращение на русском но так проще описать проблему.
Вызов оформлен следующим образом

 

>$client = new Client([
>            'baseUrl' => 'https://lk.local:48000',
>        ]);
>        $Request = $client->createRequest()
>            ->setMethod('POST')
>            ->setUrl('token')
>            ->setHeaders(['content-type' => 'application/x-www-form-urlencoded'])
>            ->setData([
>                'UserName' => 'adm',
>                'Password' => '******',
>                'Grant_type' => 'password'])
>            ->setOptions([
>            ]);
>        $response = $Request->send();
#
при попытке обращении из консольного приложения данный запрос прекрасно обрабатывается.
Но если попытатся использовать отдельный контроллер для обработки или напрямую сделать вызов из контроллера формы то появляется данная ошибка.

Я уже голову сломал пытаясь 

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.12
| Yii HTTP Client version |2.0.4.0
| PHP version             |5.5.9-1
| Operating system        |Ubuntu 14.04.5 LTS

**Comment by samdark** [comment]
Это проблема сочетания версий PHP и OpenSSL. Попробуйте обновиться: https://sourceforge.net/p/openvpn/mailman/message/29800946/
