### ISSUE TITLE
DOMDocument::loadXML(): Opening and ending tag mismatch

### ISSUE THREAD

**Issue by diegotejadav** [yiisoft/yii2-httpclient#159]
### What steps will reproduce the problem?
Making a normal request with the client
### What do you get instead?
Error:
![screen shot 2018-07-24 at 5 54 46 pm](https://user-images.githubusercontent.com/3412546/43170602-8ca7d106-8f6b-11e8-81ea-d0601f955d83.png)

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.5
| Yii HTTP Client version | 
| PHP version             | 5.5.12
| Operating system        | Windows Server 2012 R2

**Comment by Dzenefa** [comment]
she you deleted my poem video why

**Comment by diegotejadav** [comment]
I haven't been able to reproduce the error it happens sporadically, I think the API I'm consuming sometimes fails and doesn't send back a JSON response, instead of that it sends an XML, and I requested a JSON, but I'm not pretty sure.
If I get more info I'll reopen this issue.
