### ISSUE TITLE
\yiiunit\extensions\httpclient\RequestTest::testMultiPartRequest fails

### ISSUE THREAD

**Issue by alexkart** [yiisoft/yii2-httpclient#178]
\yiiunit\extensions\httpclient\RequestTest::testMultiPartRequest test fails with the following error:
```
Failed asserting that two strings are equal.
```

![40814004c6a8c863286fe5d79e5c0264](https://user-images.githubusercontent.com/8249105/56285274-7f5a1000-611f-11e9-9063-44ddae0e5b93.png)

To make such comparisons safer it's better to use:
```php
$this->assertEquals(str_replace("\r", '', $expectedPart1), str_replace("\r", '', $parts[1]));
```

I'll create a PR

**Comment by samdark** [comment]
It does not under travis: https://travis-ci.org/yiisoft/yii2-httpclient

What's your OS?

**Comment by alexkart** [comment]
Yes, I know that it fails only on some environments. My host is Windows and VM - Ubuntu.

**Comment by samdark** [comment]
We can use `assertEqualsWithoutLE()` for the purpose.

**Comment by alexkart** [comment]
Yes, it also works, it actually does the same thing, it removes '\r' and '\n' from compared strings.

**Comment by machour** [comment]
@alexkart it's unclear what OS tests are failing on for you. Could you clarify?

**Comment by alexkart** [comment]
> @alexkart it's unclear what OS tests are failing on for you. Could you clarify?

What do you mean? I specified my OS above and this test fails in my environment. After this fix, this test passes on all environments now.
