### ISSUE TITLE
Upload empty file with curl

### ISSUE THREAD

**Issue by kostychev** [yiisoft/yii2-httpclient#189]
### What steps will reproduce the problem?

```php
$file = UploadedFile::getInstance($this, 'file');

$client = new Client();
$client->setTransport(CurlTransport::class);
$fh = fopen($file->tempName, 'r');
$response = $client->createRequest()
    ->setMethod('PUT')
    ->setUrl($url)
    ->setOptions([
        CURLOPT_INFILE => $fh,
        CURLOPT_INFILESIZE => filesize($file->tempName),
        CURLOPT_BINARYTRANSFER => true,
        CURLOPT_PUT => 1,
    ])
    ->send();
fclose($fh);
```

### What's expected?

Uploaded file

### What do you get instead?

Empty file

### Additional info

It works for HTTP Client 2.0.7.

I think bug in https://github.com/yiisoft/yii2-httpclient/blob/master/src/CurlTransport.php#L148 ` $curlOptions[CURLOPT_POSTFIELDS] = $content;` because content not set.

| Q                       | A
| ----------------------- | ---
| Yii version             |  2.0.18
| Yii HTTP Client version | 2.0.9
| PHP version             | 7.1
| Operating system        | Ubuntu

**Comment by samdark** [comment]
@alexkart would you please look into it?

**Comment by alexkart** [comment]
Fixed.
