### ISSUE TITLE
official docs mentioning of this extension

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2-httpclient#19]
Is this extension mentioned anywhere in official docs? if not, shouldn't it?
I was almost using guzzle and by accident saw this here. happy to find it!

**Comment by klimov-paul** [comment]
There is no final decision about `httpclient`. As well as there is no stable release of it.
It is a subject of debates, which can be found at #2953.

So "officially" this extension does not exist yet, thus it does not mentioned anywhere.

**Comment by hesna** [comment]
Thanks for response.
