### ISSUE TITLE
Get response time

### ISSUE THREAD

**Issue by aleksandrzhiliaev** [yiisoft/yii2-httpclient#192]
Hi team, is it possible to get response time from the request in your library?

**Comment by SOHELAHMED7** [comment]
@aleksandrzhiliaev  please provide more details. Do you mean to say time calculated to generate reposne of current request?

**Comment by aleksandrzhiliaev** [comment]
I mean time to get response, so how long does it take to get answer from the server via httpClient.

**Comment by samdark** [comment]
@aleksandrzhiliaev do you want that for debugging purposes? If yes, here it is: https://github.com/yiisoft/yii2-httpclient/blob/master/docs/guide/usage-logging.md. If not then please elaborate more about your use case.

**Comment by aleksandrzhiliaev** [comment]
Nope, it is not for debugging. I want to show how long does it take to get a response. Like in curl:
https://stackoverflow.com/questions/18215389/how-do-i-measure-request-and-response-times-at-once-using-curl

**Comment by samdark** [comment]
No, there is no such feature. Do you want to add it?

**Comment by aleksandrzhiliaev** [comment]
Yes I want to add it, let me see what I can do there.

**Comment by samdark** [comment]
@aleksandrzhiliaev how is going?

**Comment by aleksandrzhiliaev** [comment]
@samdark sorry didn't have a time to look, let me try to check it on this week
