### ISSUE TITLE
For OpenSSL I can't use my cert 

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-httpclient#193]
### What steps will reproduce the problem?
Configure `requestConfig` for use my own client cert:
```
            'requestConfig' => [
                'format' => \yii\httpclient\Client::FORMAT_JSON,
                'options' => [
                    'sslVerifyPeer' => true,
                    'sslCafile' => __DIR__ . '/ssl/' . 'ca.crt',
                    'sslLocalCert' => __DIR__ . '/ssl/' . 'client01.crt',
                    'sslLocalPk' => __DIR__ . '/ssl/' . 'client01.key',
                    // 'sslPassphrase' => 'client01 crt example pass phrase',
                ],
            ],
```
Use openssl from alpine 3.9 or from debian stretch (for liberssl on alpine 3.8 all is ok)

### What's expected?
read the cert and connect to server use ssl

### What do you get instead?
can't open connection throw fopen()
```
fopen(): Unable to set local cert chain file `/var/www/html/frontend/config/ssl/client01.crt'; Check that your cafile/capath settings include details of your certificate and its issuer
```
also I got same error with curlTransport
```
Curl error: #58 - could not load PEM client certificate, OpenSSL error error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak, (no key found, wrong pass phrase, or wrong file format?)
```

May be this options not applied?

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |yiisoft/yii2                                     dev-master 0228af6 Yii PHP Framework Version 2
| Yii HTTP Client version |yiisoft/yii2-httpclient                          dev-master 3255a9b HTTP client extension for the Yii framework

| PHP version             |PHP 7.3.6 (cli) (built: May 31 2019 23:57:41) ( NTS )
( docker pull bscheshir/php:7.3.6-fpm-alpine-4yii2-xdebug )
| Operating system        | alpine3.9

https://github.com/docker-library/php/issues/844
https://github.com/openssl/openssl/issues/5098

**Comment by samdark** [comment]
Does the error differ in case you remove these options?

**Comment by bscheshirwork** [comment]
i.e. connect without ssl library? 
```
'class' => \yii\httpclient\Client::class,
```
w/o request ssl

```
            $response = $this->_client->createRequest()
                ->setMethod('post')
                ->setData($requestData)
                ->setUrl('https://github.com/yiisoft/yii2-httpclient/issues/193')
                ->send();
```

all is ok
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'">
    <meta content="origin" name="referrer">
    <title>Oh no &middot; GitHub</title>
    <meta name="viewport" content="width=device-width">
    <style type="text/css" media="screen">
      body {
        background-color: #f6f8fa;
        color: #24292e;
        font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
        font-size: 14px;
        line-height: 1.5;
        margin: 0;
      }
```

**Comment by bscheshirwork** [comment]
of course I can't pass handshake w/o cert:
400 No required SSL certificate was sent

**Comment by samdark** [comment]
Then these options are read and applied. Something else is missing from certificate/config but Yii is doing its job.

**Comment by bscheshirwork** [comment]
https://github.com/docker-library/php/issues/844#issuecomment-521953648
