### ISSUE TITLE
change CurlTransport::prepare() method from private to protected

### ISSUE THREAD

**Issue by HenryVolkmer** [yiisoft/yii2-httpclient#195]
The CurlTransport::prepare() is currently "private". So it is impossible to add custom curl-opts to a inherited Class. 

In my case, i want to implement the [CURLOPT_PROGRESSFUNCTION](https://www.php.net/manual/en/function.curl-setopt.php) by inherit CurlTransport(). But with private prepare() i have to copy/paste the whole CurlTransport-Class.

**Comment by samdark** [comment]
There's no need for it. It could be configured without changing any code:

```php
return [
    // ...
    'components' => [
        // ...
        'httpClient' => [
            'class' => 'yii\httpclient\Client',
            'requestConfig' => [
                'options' => [
                    'CURLOPT_NOPROGRESS' => false,
                    'CURLOPT_PROGRESSFUNCTION' => [ProgressHandler::class, 'handle'],
                ],
            ],
        ],
    ],
];
```

Then you can use it:

```php
Yii::$app->httpClient->createRequest() ...
```

**Comment by HenryVolkmer** [comment]
perfect! thx
