### ISSUE TITLE
RFE: please, implement handling return value from beforeSend

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2-httpclient#198]
In StreamTransport::send()
```php
public function send($request)
{
    $request->beforeSend();
    $request->prepare();
    ...
```
Also in Request::beforeSend()
```php
public function beforeSend()
{
    $this->client->beforeSend($this);
    $event = new RequestEvent();
    ...
````
We need to handle return value from `beforeSend` to cancel sending, like ActiveRecord do:
```php
protected function updateInternal($attributes = null)
{
    if (!$this->beforeSave(false)) {
        return false;
    }
    ...
```

For ex. I want to implement response caching behavior for Client. So, if response is already in cache, then onBeforeSend return false and sending must stop.

**Comment by samdark** [comment]
Sounds good. Can be released in 2.1.0 since it changes existing behavior.

**Comment by dicrtarasov** [comment]
Existing implementations return void, so, checking === false .....
Thank you :)

**Comment by cgsmith** [comment]
I know this is an old issue. Is it possible for you to use `EVENT_BEFORE_SEND` and `EVENT_AFTER_SEND` to accomplish this already? I would just create an event listener for those events and check the appropriate cache.
