### ISSUE TITLE
RFE: please, add support for http content compression (gzip, deflate, ...)

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2-httpclient#199]
Propose HTTP Compression Behavior component:

```php
/**
 * HTTP-compression support for yii\httpclient\Client
 */
class HttpCompressionBehavior extends Behavior
{
    /**
     * {@inheritdoc}
     */
    public function events()
    {
        return [
            Client::EVENT_BEFORE_SEND => '_beforeSend',
            Client::EVENT_AFTER_SEND => '_afterSend'
        ];
    }

    /**
     * Adjust request.
     *
     * @param RequestEvent $event
     */
    public function _beforeSend(RequestEvent $event)
    {
        // add accept-encoding header
        $headers = $event->request->headers;
        if (! $headers->has('accept-encoding')) {
            $headers->set('accept-encoding', 'gzip, deflate, compress');
        }
    }

    /**
     * Adjust response.
     *
     * @param RequestEvent $event
     * @throws Exception
     */
    public function _afterSend(RequestEvent $event)
    {
        $response = $event->response;
        $encoding = $response->headers->get('content-encoding');

        if ($encoding !== null) {
            $decoded = null;

            switch (strtolower($encoding)) {
                case 'deflate':
                    $decoded = @gzinflate($response->content);
                    break;

                case 'compress':
                    $decoded = @gzuncompress($response->content);
                    break;

                case 'gzip':
                    $decoded = @gzdecode($response->content);
                    break;

                default:
                    throw new Exception('unknown encode method: ' . $encoding);
            }

            if ($decoded !== false) {
                $response->content = $decoded;
            }
        }
    }
}
```

**Comment by samdark** [comment]
Does it give significant profits in terms of HTTP payload size?

**Comment by rob006** [comment]
For curl you can enable compression using `CURLOPT_ENCODING` option - it is basically transparent, you don't need to encode or decode anything, just set one option.

**Comment by dicrtarasov** [comment]
> Does it give significant profits in terms of HTTP payload size? How does it affect CPU / memory?

Basically, this brings tangible benefits for pages containing a lot of text resources (html, css, js), which are perfectly compressed. Because of transfer size, latency is reduced especially for mobile clients. Deflate the algorithm is fast enough, so the load on the web server does not increase. Especially сompared to the heavy operations of business logic (such as file I / O, working with a database), the compression costs are scanty.

> For curl you can enable compression using `CURLOPT_ENCODING` option - it is basically transparent, you don't need to encode or decode anything, just set one option.

Yes, you are right. Compression behavior, cookies persistence and many other fuches are available in CURL transport, but they are not so good documented and is hard to work with curl. Implementing simple class model or behaviors with get/setter is a good way :)
As an example, to enable supported compressions, you must set CURLOPT_ACCEPT_ENCODING to empty string (not so clear and not so documented in php).

**Comment by rob006** [comment]
I would simply enable this by default and/or add this to extension documentation. I don't see the point of creating separate behavior only for setting one option in curl transport...

**Comment by dicrtarasov** [comment]
Thank you. Let's close this.

**Comment by tom--** [comment]
So yii2-httpclient does not request compression by default and if you want it you can do something like

    ->setOptions([CURLOPT_ACCEPT_ENCODING => 'gzip, deflate'])

on a `Request` object.

Please correct me if I'm wrong.

**Comment by samdark** [comment]
Yes. Looks like it.
