### ISSUE TITLE
Getting error while trying to install using composer

### ISSUE THREAD

**Issue by chaitenyay** [yiisoft/yii2-httpclient#21]
Hello, 

While  trying to install using composer, getting following error message.

  [InvalidArgumentException]                                                                                                                               
  Could not find package yiisoft/yii2-httpclient at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

Could you please help me on this.

**Comment by cebe** [comment]
this package has no stable release yet and is not in a state where it should be used in production environment. You have to allow development version explicitly in composer.json by setting  minimum-stability  or add `@dev` to the requirement version constraint:

```json
"require": {
    ...
    "yiisoft/yii2-httpclient": "*@dev"
}
```

**Comment by chaitenyay** [comment]
Thanks Cebe. When should we expect the stable version of this package?
Can we use this package for our project, How it can affect the production?

**Comment by cebe** [comment]
We have no timeline set for this yet.
