### ISSUE TITLE
Instance with header Bearer

### ISSUE THREAD

**Issue by vitali-duckma** [yiisoft/yii2-httpclient#223]
It’s possible to create a default component instance with bearer toekn and base url? just something like this: [yii2-httpclient/usage-setup-client-instance.md at master · yiisoft/yii2-httpclient · GitHub](https://github.com/yiisoft/yii2-httpclient/blob/master/docs/guide/usage-setup-client-instance.md)

i tried but doesn’t work with header bearer.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii HTTP Client version |
| PHP version             |
| Operating system        |

**Comment by cgsmith** [comment]
@vitali-duckma I am not sure if you need this info any more... but for anyone else looking. When I need to use the HTTP client with a bearer token I just create a component class in my config file and pass the bearer token there. My component class becomes simple.  Here is an example for HubSpot.

#### /components/HubspotComponent.php
```php
<?php

namespace app\components;

use yii\base\Component;
use yii\httpclient\Client;

class HubspotComponent extends Component
{
    public Client $client;
    public string $baseUrl = 'https://api.hubapi.com';
    public string $bearerToken;

    public function init()
    {
        parent::init();

        $this->client = new Client([
            'baseUrl' => $this->baseUrl,
            'requestConfig' => [
                'format' => Client::FORMAT_JSON,
            ],
            'responseConfig' => [
                'format' => Client::FORMAT_JSON,
            ],
        ]);

        // Setup event for auth before each send
        $this->client->on(Client::EVENT_BEFORE_SEND, function ($event) {
            $event->request->addHeaders(['Authorization' => 'Bearer ' . $this->bearerToken]);
        });
    }

    /** Method calls to HubSpot API */
}
```

#### config/main.php

```php
return [
     'components' => [
        'hubspot' => [
            'class' => HubspotComponent::class, 
            'bearerToken' => $params['hubspot.bearerToken'],
        ]
    ],
];
```

#### config/params.php

```php
<?php
return [
    'hubspot.bearerToken' => 'your-token-here',
];
```
