### ISSUE TITLE
Shorcut Get methd  with params generates a malformed request (Your client has issued a malformed or illegal request)

### ISSUE THREAD

**Issue by matias-yii** [yiisoft/yii2-httpclient#228]
### What steps will reproduce the problem?
Use shortcut methods get() with any params 
for ex. 

```php
$client = new Client(['baseUrl' => 'http://example.com/api/1.0']);
$articleResponse = $client
    ->get('articles', ['name' => 'Yii'])
    ->addHeaders(['header' => 1])
    ->setFormat(Client::FORMAT_JSON)
    ->setOptions(['timeout' => 10])
    ->send();
```

### What's expected?
the request on the sever should be http://example.com/api/1.0/articles?name=Yii
the body of the request should be empty
there should not be a content-length header field

### What do you get instead?
the request on the server is http://example.com/api/1.0/articles
with the body content raw {\"name\":\"Yii\"}
a content-length header is set in the header request
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version      2.0.47       |
| Yii HTTP Client version  2.0.14|
| PHP version      8.1.2       |
| Operating system   Linux      |

**Comment by samdark** [comment]
Any idea about why is that?

**Comment by matias-yii** [comment]
The example was incomplete, i fixed. It happens only when you use the get method with setFormat option.

**Comment by cgsmith** [comment]
Hi @matias-yii 

I ran the following code on PHP 8.1.29 without any issues.

https://webhook.site is a good spot to see how the responses come through. I attached my result.

```php
$client = new Client(['baseUrl' => 'https://webhook.site/xxxxx-8678']);
        $response = $client
            ->get('articles', ['name' => 'Yii'])
            ->addHeaders(['header' => 1])
            ->setFormat(Client::FORMAT_JSON)
            ->setOptions(['timeout' => 10])
            ->send();
 ```
 
 
![image](https://github.com/user-attachments/assets/318ae213-423c-4f8f-b424-8e50ce82c69d)
