### ISSUE TITLE
No versions in this repo?

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2-httpclient#23]
I look the versions tab (since I noticed composer said there was no 2.0.0) and the releases tab here is completely empty.

Is this expected?

**Comment by SilverFire** [comment]
Yes, we are going to release it.

**Comment by samdark** [comment]
Or not :)

**Comment by Sammaye** [comment]
Heh, is that because the project could move or be merged or something or is it just one of those thangs?

I'll just update this dep very rarely :P

**Comment by samdark** [comment]
It's because of PSR-7 compatibility and existence of Guzzle.

**Comment by samdark** [comment]
While Paul invested lots of time in it I'm not sure it's a good idea to promote it as official Yii library. It makes sense in case we can make something better than existing solutions and this time I'm not sure it's the case. The library it's not compatible with PSR-7 and lacks features compared to well-maintained competitor: Guzzle.

**Comment by Sammaye** [comment]
This is definitely good for small programs. Like we have a script that doesn't need the hog that is Guzzle but needs a decent library that isn't a mix and match.

So this library could be useful even if for serious work you would use Guzzle

**Comment by samdark** [comment]
Yes. I'm not saying it's bad. It's definitely not.
