### ISSUE TITLE
Unrecognized format 

### ISSUE THREAD

**Issue by asadbekuzz** [yiisoft/yii2-httpclient#244]
### What steps will reproduce the problem?
When I the resquest the server, I have the error message for spesific endpoint
### What do you get instead?
Unrecognized format ''","Code: 0\nFile: D:\\...\\vendor\\yiisoft\\yii2-httpclient\\src\\Client.php\nLine: 178

| Q                       | A
| ----------------------- | ---
| Yii version             |  2.0.14
| Yii HTTP Client version |  2.0.13
| PHP version             | 7.4
| Operating system        | windows 10

**Comment by bizley** [comment]
Please provide the minimal amount of code to reproduce it. So far we can only see that your set format is empty.

**Comment by asadbekuzz** [comment]
> Please provide the minimal amount of code to reproduce it. So far we can only see that your set format is empty.

Thank you for attention. I've solved the problem that i make.
