### ISSUE TITLE
Installation Instructions : require dev-master ?

### ISSUE THREAD

**Issue by manquer** [yiisoft/yii2-httpclient#25]
Instructions suggest using  `"yiisoft/yii2-httpclient": "~2.0.0"` however no release has been made therefore this  does not work , docs to reflect correct usage, until release is made?

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2-httpclient/issues/23

**Comment by manquer** [comment]
@SilverFire the current usage instructions are misleading, whether to be released or what to be included in the release , or when to include the tag in the repo is entirely different discussion. as in #23. 

The point of this issue is that as current  *instructions*  is misleading/wrong on both installation procedure as well as state of the repository/project (still under development).

If and when you do tag the project, then recommending ` ~2.0.0 ` is okay, but it is not as things stand.

**Comment by cebe** [comment]
This repo is not ready to use so IMO it is fine if installation fails and you have to think twice if you really want it.

**Comment by manquer** [comment]
@cebe If you feel the repo is not ready then don't you think at least some sort of warning in the README that this is not production ready is a good idea? Would it not be better for other noobs like me to be warned straightway than waste every1's time?

**Comment by SilverFire** [comment]
I think it's a basis of versioning using composer. Every noob who wants to work with composer should learn these things to do work well.

**Comment by hscstudio** [comment]
``` Every noob who wants to work with composer should learn these things to do work well.```

:-1: We only suggest to release because this is good extension. huft :(

**Comment by cebe** [comment]
@hscstudio we are not going to release it until it has been reviewed and we find it has the required quality. Currently we need to focus on already released stuff that needs maintainance.

**Comment by manquer** [comment]
it would prevent these issues being filed repeatedly, if you put a warning it is under development atleast in README as was practice in core repo until stable release
