### ISSUE TITLE
Http cache (304 not modified)

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2-httpclient#28]
Нужна добавить возможность кэширования ответа от сервера, с помощью http загаловков.
`"yiisoft/yii2": "*"` сейчас присутствует в зависимостях, поэтому для хранения можно использовать интерфейс `yii\caching\Cache`

PS у `"yiisoft/yii2": "*"` желательно указать фиксированую версию.

**Comment by klimov-paul** [comment]
Will not be implemented: it requires put every response into a cache.
Since #43, you can create a behavior for this functionality.

**Comment by LAV45** [comment]
@klimov-paul , how do you like this implementation of the event [beforeGetValue()](https://github.com/LAV45/yii2-settings/blob/master/src/Settings.php#L160) ?

**Comment by klimov-paul** [comment]
'Before get value' of what?

**Comment by LAV45** [comment]
This is similar to the method [beforeSend()](https://github.com/yiisoft/yii2-httpclient/blob/master/Client.php#L365)

**Comment by LAV45** [comment]
```php
    public function beforeSend($request)
    {
        $event = new RequestEvent();
        $event->request = $request;
        $this->trigger(self::EVENT_BEFORE_SEND, $event);
        return $event->response;
    }
```
If behavior returned `$event->response !== null` then it can be returned without performing of the http request.

**Comment by klimov-paul** [comment]
> can be returned without performing of the http request.

I don't get it. '30x' response status either processed automatically at 'stream' or 'CURL' library level or return as it is. If you enable `followLocation` library will automatically perform second request without any ability to interfere from outside, if you disable it - the response with '30x' status will be returned as it is, and you can process it as you like.
