### ISSUE TITLE
Setting unknown property: yii\web\Cookie::max-age

### ISSUE THREAD

**Issue by itilev** [yiisoft/yii2-httpclient#29]
При загрузки страницы с сервера на котором установлен PHP 5.5.x в заголовок Set-Cookie теперь добавляется еще атрибут Max-Age - http://php.net/manual/ru/function.setcookie.php#refsect1-function.setcookie-changelog и соответственно при разборе возникает эта ошибка.

**Comment by samdark** [comment]
Как воспроизвести?

**Comment by itilev** [comment]
<?php

use yii\httpclient\Client;

$client = new Client();
$response = $client->get( 'http://www.tilev.ru/yii-maxage.php' )->send();
var_dump($response->getCookies());

**Comment by klimov-paul** [comment]
Resolved by commit cc493475c4c6f51b7157062f54c2697ca3e3ca69
