### ISSUE TITLE
Fix phpdoc comments to be more IDE friendly

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2-httpclient#37]
In `yii\httpclient\Request` majority of methods return `$this` for method chaining and their phpdoc says `@return $this self reference`. This is not IDE friendly and PHPStorm for example can't type hint chaining, it actually says that `can't find methods in class '$this'`.

Consider doc example
````
$response = $client->createRequest()
    ->setMethod('post')
    ->setUrl('http://domain.com/api/1.0/users')
    ->setData(['name' => 'John Doe', 'email' => 'johndoe@domain.com'])
    ->send();
````
Everything after `setMethod` is not working (type hinting) in PHPStorm.
Consider changing the phpdoc to `@return self` or `@return Request` for normal type hinting.

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/7045
