### ISSUE TITLE
Empty body on GET requests

### ISSUE THREAD

**Issue by AnatolyRugalev** [yiisoft/yii2-httpclient#39]
I'm experiencing problems after fresh update.

Looks like `GET` method [here](https://github.com/yiisoft/yii2-httpclient/commit/f17ba9780a3a45d9fa434981034a38be9394e27e#diff-56cdc9597eabff19e0b13b80922fad6eR133) is redunant

**Comment by klimov-paul** [comment]
Which problems?

**Comment by AnatolyRugalev** [comment]
@klimov-paul After update `Response` object always contains empty `$content` after `GET` request.

```php
$response = Yii::$app->httpclient->get('http://httpbin.org/get')->send();
var_dump($response->getStatusCode()); // string(3) "200"
var_dump($response->getContent()); // string(0) ""
```

**Comment by klimov-paul** [comment]
99f68c98cb52cc2e5df3c820842592b4b5467fa8

**Comment by AnatolyRugalev** [comment]
Thank you!
