### ISSUE TITLE
PSR-7 Compatibility

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-httpclient#4]
Consider make solution compatibable with PSR-7:
http://www.php-fig.org/psr/psr-7/

**Comment by klimov-paul** [comment]
I am usure pursuite of the PSR-7 makes sense. 
This standard requires complex solid appraoch and interface, which is uncommon for Yii.
For example it requires usage of `UriInterface` for URL specification,  `StreamInterface` for any file involved etc.
Also PSR-7 dictates not only sending HTTP messages but thier general handling. Applying this standard actually requires refactoring of the `yii\web\*` package.

Althouhg some parts of PSR-7 can be applied - I don't think is worth it.

**Comment by farmani** [comment]
so what's the point of being part of the PSR if we don't want to implement it?

**Comment by cebe** [comment]
> being part of the PSR

what do you mean?

**Comment by farmani** [comment]
Sorry it was being a member of php-fig

**Comment by samdark** [comment]
PSR-7 is more about routers and overall is about interoperability. It's not end user interface.

**Comment by farmani** [comment]
I agree with @klimov-paul that understanding and implementing PSR-7 is difficult and it's not common in Yii but it's not a good reason to not do it.

honestly I don't get your point @samdark 

> PSR-7 is more about routers and overall is about interoperability.

yes this is why we are using PSRs "interoperability" and soon or later we will do it so why not today?

> It's not end user interface.

So, I'm not sure what's your plan for httpclient extension if it's an http client like guzzle I think it's better to use standards and I think this manner should continue in other core/extensions too like PSR-6 for cache interfaces.

**Comment by klimov-paul** [comment]
This extension reuses classes declated at `yii\web\*`.
PSR-7 covers not just HTTP client - it covers HTTP request, HTTP response, Cookies, Headers and URLs.
If we want to follow PSR-7, we should start from reworking classes under `yii\web\*`. Only when classes like `yii\web\Response` start follow PSR-7, we can think about `yii-httpclient` to follow it as well.

**Comment by farmani** [comment]
I think there is just a number of that * should rewrite many of them related to assets, session, and etc.

**Comment by samdark** [comment]
Yes. Well, that's an option for another big milestone...

**Comment by klimov-paul** [comment]
Resolved at [branch 2.1](https://github.com/yiisoft/yii2-httpclient/tree/2.1)
