### ISSUE TITLE
CURLINFO, Url, LastUrl

### ISSUE THREAD

**Issue by G1K** [yiisoft/yii2-httpclient#40]
Было бы хорошо иметь возможность к доступу данных CURLINFO, Например к 
CURLINFO_EFFECTIVE_URL

В результирующих данных, полезно иметь запрашиваемый Url в качестве одного из атрибутов.
При редиректе хорошо получать и конечный Url.

**Comment by klimov-paul** [comment]
This will not be implemented since CURL is only one of available transports.
