### ISSUE TITLE
Exceptions name collision

### ISSUE THREAD

**Issue by Devdits** [yiisoft/yii2-httpclient#44]
Hello,
Today I catch error: "Fatal error:  Cannot use yii\base\Exception as Exception because the name is already in use in /path/to/project/vendor/yiisoft/yii2-httpclient/Response.php on line 10"

In last version (2.0.0.1) was added class yii\httpclient\Exception, but in same namespace "yii\httpclient" in class Response.php me have next code: "use yii\base\Exception;". And now in Response.php we have two classes with same name: "Exception".

**Comment by cebe** [comment]
fixed, thanks for reporting!
