### ISSUE TITLE
Зачем?

### ISSUE THREAD

**Issue by iiifx** [yiisoft/yii2-httpclient#48]
Ну правда, просто интересно. Зачем был сделан? Есть же современные, качественные альтернативы.

**Comment by samdark** [comment]
Данное расширение — легковесная обёртка с двумя легковесными драйверами. Хотите Guzzle — можете сделать драйвер под него.

**Comment by iiifx** [comment]
Я думал может расширение дает какое-то особое преимущество в рамках фреймворка в сравнении с другими клиентами.

Спасибо за ответ.

**Comment by samdark** [comment]
Даёт, конечно. Дебаг-панельку добавляет как минимум.
