### ISSUE TITLE
How do I specify the HTTP request version to 1.1

### ISSUE THREAD

**Issue by appcodr** [yiisoft/yii2-httpclient#50]
I am trying to make a REST API request to Azure Blob service and I get an UnsupportedHttpVersion error when making the call using the httpclient extension. This is the code I use

      $client = new Client(['baseUrl' => $uri]);
      //    $client = new Client();
        $request = $client->createRequest()
                ->setUrl($urlPath)
                ->setHeaders( [
                    'x-ms-date' => $dateTime,
                    'x-ms-version' => '2013-08-15',
                    'Authorization' => $auth,
                ] )
                ->setMethod( 'GET' );
        var_dump($request);
        $response = $request->send();

When I make the same request from a POSTMAN REST client, it works perfectly and it says HTTP1.1 when I see what it sends. But I am not sure how I set this using this extension.

Any ideas?

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0
| PHP version      | 5.5
| Operating system | Ubuntu

**Comment by appcodr** [comment]
I used set options method to set CURLOPT_HTTP_VERSION to CURL_HTTP_VERSION_1_1 and it worked. I have to set the transport to curl transport. Is this the right approach? Or is there a header or something that I can set to HTTP 1.1?

`        $client = new Client([
    'transport' => 'yii\httpclient\CurlTransport' // only cURL supports the options we need
]);
        $request = $client->createRequest()
                ->setUrl($urlPath)
                ->setHeaders( [
                    'x-ms-date' => $dateTime,
                    'x-ms-version' => '2013-08-15',
                    'Authorization' => $auth,
                ] )
                ->addOptions([
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                ])
                ->setMethod( 'GET' );`

**Comment by klimov-paul** [comment]
Resolved by commit 83599c331aee14ce9adcd03eff5d0a02f59379d8
