### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Yii' not found

### ISSUE THREAD

**Issue by Olegf13** [yiisoft/yii2-httpclient#51]
### What steps will reproduce the problem?
```
<?php
require __DIR__ . '/vendor/autoload.php';

use yii\httpclient\Client;

$client = new Client(['baseUrl' => 'http://example.com/api/1.0']);
```

### What's expected?
Client object creation.

### What do you get instead?
```
Fatal error: Uncaught Error: Class 'Yii' not found in ...
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 7.0.8-4
| Operating system | Ubuntu 16.04

**Comment by klimov-paul** [comment]
Unable to reproduce.

**Comment by Olegf13** [comment]
Why is it unable to reproduce? I'm doing an example from `basic usage` page ([here](https://github.com/yiisoft/yii2-httpclient/blob/master/docs/guide/basic-usage.md)).

Can add my `composer.lock` file if is needed.

**Comment by klimov-paul** [comment]
Extension function is covered by unit tests, which are passing correctly:
https://travis-ci.org/yiisoft/yii2-httpclient

I have also checked Client creation manually - it works fine.

**Comment by Olegf13** [comment]
As you commented [at Yii2 issue](https://github.com/yiisoft/yii2/issues/12011#issuecomment-234937686), I understand that in here I also need to import Yii with the following line below?
```
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
```
