### ISSUE TITLE
PHP Notice (and Warning) on POST requests

### ISSUE THREAD

**Issue by Olegf13** [yiisoft/yii2-httpclient#52]
### What steps will reproduce the problem?

```
<?php
require __DIR__ . '/vendor/autoload.php';
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

use yii\httpclient\Client;

$client = new Client();
$response = $client->createRequest()
    ->setMethod('post')
    ->setUrl('http://example.com/api/1.0/users')
    ->setData(['name' => 'John Doe', 'email' => 'johndoe@example.com'])
    ->send();
```

### What's expected?

Safe run.

### What do you get instead?

```
Notice: Trying to get property of non-object in vendor/yiisoft/yii2/helpers/BaseStringHelper.php on line 111
Warning: mb_strlen(): Unknown encoding "" in vendor/yiisoft/yii2/helpers/BaseStringHelper.php on line 111
```

### Additional info

This Yii method is called from `/var/www/sandbox.dev/vendor/yiisoft/yii2-httpclient/Client.php:257`.

Issue is reproduced only on POST requests (not on GET ones).

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 7.0.8-4
| Operating system | Ubuntu 16.04

**Comment by klimov-paul** [comment]
You should instantiate an Yii application before usage.
