### ISSUE TITLE
Неправильное отображение на дебаг тулбаре

### ISSUE THREAD

**Issue by rahimov** [yiisoft/yii2-httpclient#55]
Исправления в пулл-реквесте

https://github.com/yiisoft/yii2-httpclient/pull/54

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 7.0.8
| Operating system | CentOs

**Comment by samdark** [comment]
Неправильное отображение чего?

**Comment by klimov-paul** [comment]
Resolved via #54
