### ISSUE TITLE
UrlEncodeFormatter charset support

### ISSUE THREAD

**Issue by gxguo** [yiisoft/yii2-httpclient#58]
when i use this urlencodeformatter for chinese language,i can't change the charset to utf-8;
so i need to change the code, line 50 to this " **$request->getHeaders()->set('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');**"

**Comment by klimov-paul** [comment]
Resolved by commit 8f05027e3b94d2173461651f66d9b360e9353f7c
