### ISSUE TITLE
Sending twice, got double params

### ISSUE THREAD

**Issue by n3yang** [yiisoft/yii2-httpclient#59]
### What steps will reproduce the problem?
Sending twice, got double params? its a bug or not. I am not sure.

```php
$client = new Client(['transport' => 'yii\httpclient\StreamTransport']); // same to setup yii\httpclient\CurlTransport
$request = $client->createRequest()
    ->setUrl('http://localhost')
    ->setMethod('get')
    ->setData(['k'=>'v']);
$request->send();
$request->send();
$request->send();
```
in access log file, I got:
```
"GET /?k=v HTTP/1.0" 200 41686 "-" "-"
"GET /?k=v&k=v HTTP/1.0" 200 41694 "-" "-"
"GET /?k=v&k=v&k=v HTTP/1.0" 200 41702 "-" "-"
```
### What's expected?
Same requested params.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.9
| Yii http client       |2.0.0
| PHP version      |5.6.20
| Operating system |OSX

**Comment by klimov-paul** [comment]
It is already fixed at the 'master'
