### ISSUE TITLE
[ ASK ][ FILE:// ] file_get_contents(): remote host file access not supported

### ISSUE THREAD

**Issue by atmanegara** [yiisoft/yii2-httpclient#60]
ok , my script

http://pastebin.com/d1QkLQZq

on localhost, it's work perfect , but in web hosting, show error

`file_get_contents(): remote host file access not supported`

planning, upload file from dekstop application/local drive my computer to hosting **using File://**

Please help me sir

**Comment by klimov-paul** [comment]
@atmanegara, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
