### ISSUE TITLE
It send http request via http 1.0 protocal. yiisoft/yii2-httpclient

### ISSUE THREAD

**Issue by yelvxiuge** [yiisoft/yii2-httpclient#65]
### What steps will reproduce the problem?
More error occured when call some url via  yiisoft/yii2-httpclient

### What's expected?
It use http 1.0 to send requests
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |
| PHP version      |
| Operating system |

**Comment by klimov-paul** [comment]
Duplicates #50
