### ISSUE TITLE
Response::defaultFormat() can return NULL

### ISSUE THREAD

**Issue by dotterian** [yiisoft/yii2-httpclient#67]
### What steps will reproduce the problem?
In some cases [Response::defaultFormat()](https://github.com/yiisoft/yii2-httpclient/blob/master/Response.php#L84) can return NULL and therefore [Response::getParser()](https://github.com/yiisoft/yii2-httpclient/blob/master/Response.php#L189) will throw exception.

### What's expected?
I'd like to get Client::RAW_URLENCODED instead of Exception and operate with raw response.
Maybe just make it configurable in component config.

**Comment by klimov-paul** [comment]
Will not be changed.
You can get raw response using `Response::getContent()`, only `Response::getData()` will trigger parser.
