### ISSUE TITLE
it's possible logging response?

### ISSUE THREAD

**Issue by markmarco16** [yiisoft/yii2-httpclient#69]
Hello again, it's possible logging response similar to [Doc Logging](https://github.com/yiisoft/yii2-httpclient/blob/master/docs/guide/usage-logging.md)?

I used third party services and i would like saved reponse their response.

Thanks!

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-httpclient/blob/master/docs/guide/usage-logging.md
