### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-httpclient#7]
I have complete the extension.
Now it requires review from the @yiisoft/core-developers and potential users.
I suppose at least 2 members of the core team should provide thier feedbacks before release.
Feel free to open issues for the inconsistencies or other problems found.

**Comment by Ragazzo** [comment]
@klimov-paul in various situations it can be need to set different timeouts for connect and for data receive, is it supported now? Similar like it is done in [ZF2](https://github.com/zendframework/zend-http/blob/master/src/Client/Adapter/Curl.php#L198)

**Comment by klimov-paul** [comment]
You can setup those if you are using `TransortCurl`, but for `TransportStream` there is only one 'timeout' option.

**Comment by Ragazzo** [comment]
is it anywhere in the docs, would be nice to have it?

**Comment by uniqby** [comment]
@Ragazzo https://github.com/yiisoft/yii2-httpclient/tree/master/docs/guide

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-httpclient/blob/master/Request.php#L75

**Comment by Ragazzo** [comment]
i mean use - case in docs how to specify two different timeouts, simple comment line is not that helpful i think

**Comment by klimov-paul** [comment]
> You may set options using keys, which are specific to particular transport, like `[CURLOPT_VERBOSE => true]` in case there is a necessity for it.

**Comment by Ragazzo** [comment]
ok, i will say in other way around, can you add an example?

**Comment by klimov-paul** [comment]
976fb30

**Comment by Ragazzo** [comment]
Thank you

**Comment by golovanov** [comment]
I disagree with the name of the classes TransportCulr, TransportStream, ParserJson, FormatterJson, etc.
Other classes in Yii in general have the next name format - \<Type\>  or \<\<Subtype\>Type\>

Example:
- Validator, EmailValidator, StringValidator, SafeValidator, ...
- Session, CacheSession, DbSession, ...
- Action, ErrorAction, CaptchaAction, ...
- Exception, ConflictHttpException, ForbiddenHttpException, ...
- ...

I suggest to change the next classes to general name format:
- FormatterJson => JsonFormatter
- FormatterUrlEncoded => UrlEncodedFormatter
- FormatterXml => XmlFormatter
- ParserJson => JsonParser
- ParserXml => XmlParser
- ParserUrlEncoded => UrlEncodedParser
- TransportCurl => CurlTransport
- TransportStream => StreamTransport

**Comment by klimov-paul** [comment]
> I disagree with the name of the classes TransportCulr, TransportStream, ParserJson, FormatterJson, etc.
Other classes in Yii in general have the next name format - <Type> or <<Subtype>Type>

Could you please open a separated issue for the naming convension?

**Comment by creocoder** [comment]
> or other problems found

The main trouble is reinventing wheels and useless :) Everything other looks OK :+1: 

I'll explain useless aspect more. There is another much more famous and mature http clients like Guzzle. Any worth for any company and any user to invest time for learn new api.

**Comment by samdark** [comment]
- https://github.com/yiisoft/yii2-httpclient/blob/master/TransportCurl.php#L140 composeHeaderLines() has not arguments but $request is passed. Same at https://github.com/yiisoft/yii2-httpclient/blob/master/TransportStream.php#L48.
- https://github.com/yiisoft/yii2-httpclient/blob/master/Client.php#L231 could array in signature as well or should be declared as string|array is the intent was to allow a single string header (which I think is not a good idea).

Also I've made some minor fixes:

- Removed unused imports.
- Simplified regexps a bit.
- Changed comparison to strict ones where possible.

Not high-level review yet...

**Comment by klimov-paul** [comment]
> composeHeaderLines() has not arguments but $request is passed. Same at...
> could array in signature as well or should be declared as string|array is the intent was to allow a single string header (which I think is not a good idea).

Fixed: 32e60c3

**Comment by AnatolyRugalev** [comment]
@creocoder Because all packages for yii uses it's own curl wrapper... Some of them ignores SSL errors, which may cause application security problems. In core of yii:

* yii2-authclient
* yii2-swiftmailer
* <any other extenal service extension>

We are using more than 10 different libraries which works with HTTP. All of them has `yii2-` prefix. Some of them using Guzzle but in the most cases its another low-quality wrapper for CURL. In some cases, different libraries depends from different major Guzzle version, and this is a big trouble. :sob: 

I think the best way is to provide one framework based interface, which can use Guzzle or any other library as a transport. Just my opinion.

**Comment by klimov-paul** [comment]
I consider this one complete.
