### ISSUE TITLE
setData param with $

### ISSUE THREAD

**Issue by totpero** [yiisoft/yii2-httpclient#71]
Hello,

I try to access this URL: 
`http://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='log4net'&targetFramework=''&includePrerelease=false`

using this piece of code:

```
$client = new Client(['baseUrl' => 'http://nuget.org/']);
$response = $client->createRequest()
	->setFormat(Client::FORMAT_XML)
	->setUrl('api/v2/Search()')
	->setData([
		'$top' => '30',
	])
	->send();

$responseData = $response->getData();
```
and i get this error:

```
<name>Exception</name>
<message>Invalid Character Error</message>
<code>5</code>
<type>DOMException</type>
<file>C:\Program Files (x86)\Ampps\www\app-update\vendor\yiisoft\yii2-httpclient\XmlFormatter.php</file>
<line>104</line>
<stack-trace>
	<item>#0 C:\Program Files (x86)\Ampps\www\app-update\vendor\yiisoft\yii2-httpclient\XmlFormatter.php(104): DOMElement->__construct('$top')</item>
	....
```

The error is from `$` character because if i remove this works fine.

**Comment by klimov-paul** [comment]
XML document tags can not start from `$`, see:
http://www.w3schools.com/xml/xml_elements.asp

Thus your request can not be packed in valid XML document. Current behavior is expected in this case and will not be changed.

> I try to access this URL: 
http://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='log4net'&targetFramework=''&includePrerelease=false

Why are you using XML format for the request then? Seems it should be regular URL encoded query string.

**Comment by totpero** [comment]
the response of this url is valid xml (is rss). The problem is query string parameters start with $ character not the xml response.

GET parameters: 
**$**filter=IsLatestVersion&
**$**orderby=Id
....
and when i try to add this query data like this:

```
->setData([
        '$filter' => 'IsLatestVersion',
    ])
```
crash.

**Comment by klimov-paul** [comment]
If you so sure, then provide answers to the following questions:

1) How does your request look like in logs?
2) What happens if you use code without `->setFormat(Client::FORMAT_XML)`?

```php
$client = new Client(['baseUrl' => 'http://nuget.org/']);
$response = $client->createRequest()
    ->setUrl('api/v2/Search()')
    ->setData([
        '$top' => '30',
    ])
    ->send();

$responseData = $response->getData();
```

**Comment by totpero** [comment]
If i use like this works:
```
$client = new Client(['baseUrl' => 'http://nuget.org/']);
$response = $client->createRequest()
    ->setUrl('api/v2/Search()')
    ->setData([
        '$top' => '30',
    ])
    ->send();

$responseData = $response->getData();
```
also if i use like this works:

```
$client = new Client(['baseUrl' => 'http://nuget.org/']);
$response = $client->createRequest()
    ->setFormat(Client::FORMAT_XML)
    ->setUrl('api/v2/Search()')
    ->send();

$responseData = $response->getData();
```

but if i use both don't works:

```
$client = new Client(['baseUrl' => 'http://nuget.org/']);
$response = $client->createRequest()
    ->setFormat(Client::FORMAT_XML)
    ->setUrl('api/v2/Search()')
    ->setData([
        '$top' => '30',
       ])
    ->send();

$responseData = $response->getData();
```
 i get error:

```
<name>Exception</name>
<message>Invalid Character Error</message>
<code>5</code>
<type>DOMException</type>
<file>C:\Program Files (x86)\Ampps\www\app-update\vendor\yiisoft\yii2-httpclient\XmlFormatter.php</file>
<line>104</line>
<stack-trace>
    <item>#0 C:\Program Files (x86)\Ampps\www\app-update\vendor\yiisoft\yii2-httpclient\XmlFormatter.php(104): DOMElement->__construct('$top')</item>
    ....
```

**Comment by cebe** [comment]
`setData()` is for the request body. if you want to create a URL like you showed above that does not belong to the body, but to the URL. The $ will be added to **request** body, not to the response body in your code.

**Comment by totpero** [comment]
1. setData is only for POST method not for GET?
2. If i use   ` ->setMethod('GET')` the  `->setData(...` add my parameters to url like this: `/api/v2/Search()?$top=30...` and if i use  ` ->setMethod('POST')` add my parameters to request body and this is what is in my case?

In this issue https://github.com/yiisoft/yii2-httpclient/issues/70 i see using:
```
->setUrl([
                'http://someRestApi',
                'access-token' => '123',
            ])
```
with:
```
 ->addData([
                'object_id' => 52,
                'name' => 'qweqe',
            ])
```
How is correctly to use?
