### ISSUE TITLE
Content buffer too small

### ISSUE THREAD

**Issue by garyhensley** [yiisoft/yii2-httpclient#72]
I'm using this to read webservice calls that return json, but the data buffer is too small.  I am not getting the entire json response with $response->content.  When I export the contents out to a log file it is truncating the json response.  I'm only receiving 188K of the 543K lines I should be receiving from the webservice for the sample that is erroring.

NO, I can't break it into smaller parts.  This is 3rd party webservice.

**Comment by cebe** [comment]
which buffer are you talking about? also please show the code that you are using to retrieve the data.

**Comment by garyhensley** [comment]
Disregard.  I'm getting it this issue with other libraries as well.  It seems to be some issue with the website I'm reading from.
