### ISSUE TITLE
Request body not updating after first request

### ISSUE THREAD

**Issue by rkoblev** [yiisoft/yii2-httpclient#74]
### What steps will reproduce the problem?
       $client = new Client();
        $request = $client->createRequest()
            ->setUrl('http://google.com')
            ->setMethod('post');
        $request->setData(['param1' => 1])->send();
        $request->setData(['param1' => 2])->send();
### What's expected?
```
POST http://google.com
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

param1=1
```
```
POST http://google.com
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

param1=2
```
### What do you get instead?
```
POST http://google.com
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

param1=1
```
```
POST http://google.com
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

param1=1
```
### Why this happens?
`Request.php::prepare()` line 229
```php
$content = $this->getContent();
        if ($content === null) {
            $this->getFormatter()->format($this);
```
Before first request `$content` is null, but before second request `$content` is not null, so request body not updating
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.10
| Yii HTTP Client version | 2.0.2
| PHP version             | 7.0.12
| Operating system        | Debian 8

**Comment by klimov-paul** [comment]
Resolved by commit 73ce827f04f7aeadb70e0edb2373c6e444e21b07
