### ISSUE TITLE
Why $response->getIsok() throw Exception when Request Failed ?

### ISSUE THREAD

**Issue by ihipop** [yiisoft/yii2-httpclient#75]
Why $response->getIsok() throw Exception when Request Failed ?

https://github.com/yiisoft/yii2-httpclient/blob/master/Response.php#L68

`$response->getIsok()` call `getStatusCode()` which throw Exception when there is no `http-code`

if a  `Request Failed` happened ,and **there is necessary to throw an Exception** , why not throw it immediately  after `Request Failed`?

**Comment by klimov-paul** [comment]
Duplicates #61

**Comment by ihipop** [comment]
@klimov-paul it's not Duplicates

I'm talking about a `Exception ` strategy  ***when  there is necessary to throw an Exception***

**Comment by klimov-paul** [comment]
Provide the steps to reproduce your problem, then.
