### ISSUE TITLE
Adding http debug panel will cause a Warning when access the old debug log

### ISSUE THREAD

**Issue by ihipop** [yiisoft/yii2-httpclient#76]
### What steps will reproduce the problem?
debug without `yii2-httpclient` installed to generate  `history debug data`
then install  yii2-httpclient ,and  add `http debug panel` configuration in config/main.php to enable 
`http debug panel`
### What's expected?
 `history  generated debug data` can be access with no warning
Everything thould be ok 

### What do you get instead?
![image](https://cloud.githubusercontent.com/assets/423077/20385255/b5f9ef3e-acf1-11e6-9012-d44e56f9d028.png)
An php Warning Occs when access to `history  generated debug data`  because there is no httpclient  generated in previous data, and `$this->data['messages']` is not an array in https://github.com/yiisoft/yii2-httpclient/blob/master/debug/HttpClientPanel.php#L125

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.5
| Yii HTTP Client version | 2.0.2
| PHP version             |  PHP 5.6.25 with debug enabled
| Operating system        | Ubuntu 16.04 LTS

**Comment by klimov-paul** [comment]
Resolved by commit 34f2d241d4057a4be3bb168c4b0effea352ae307
