### ISSUE TITLE
override "Content-type" if method is POST

### ISSUE THREAD

**Issue by MaksimSkomorokh** [yiisoft/yii2-httpclient#78]
### What steps will reproduce the problem?
```
$headers = [
    'Authorization' => 'bearer 34324-933d-234-985d-344343434'
    'Accept' => 'application/json'
    'Content-Type' => 'application/json'
];
$data = [
'username'=>'Ivanov',
'first_name'=>'Igor'
]
$url = $this->apiUrl . "/user/{$userId}/profile/";
$request = $this->createRequest()
         ->setMethod('POST')
         ->setUrl($url)
         ->setHeaders($headers)
         ->setData($data);
```

### What's expected?
```
GET http://hostname.com/v1/user/123/profile/ 

Authorization: bearer 34324-933d-234-985d-344343434 

Accept: application/json 

Content-Type: application/json
```

### What do you get instead?
```
GET http://hostname.com/v1/user/123/profile/ 

Authorization: bearer 34324-933d-234-985d-344343434 

Accept: application/json 

**Content-Type: application/x-www-form-urlencoded; charset=UTF-8**
```
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.1
| Yii HTTP Client version | 2.0.2
| PHP version             | 7
| Operating system        | windows

**Comment by klimov-paul** [comment]
You should either use `Request::setContent()` or set format to be JSON using `Request::setContent()`.

**Comment by MaksimSkomorokh** [comment]
Could you pls update my code to show how it should looks.
http://www.yiiframework.com/doc-2.0/yii-web-request.html doesn't have setContent() method. Thanks

**Comment by klimov-paul** [comment]
`yii\web\Request` has nothing to do with `yii2-httpclient`. This extension operates `yii\httpclient\Request`.
