### ISSUE TITLE
error prepare url 

### ISSUE THREAD

**Issue by sanchezzzhak** [yiisoft/yii2-httpclient#79]
### What steps will reproduce the problem?
not correct url preparing  on the final stage
test 1
```php
$url = 'http://test-ch@localhost?database=default';
$client = new Client([
   'baseUrl' => $url,
   transport' => 'yii\httpclient\CurlTransport'
]);
 $rawSql = "select 1";
 $response =  $client
           ->createRequest()
           ->setMethod('POST')
           ->setContent($rawSql)
           ->send();
```
you  send client `http://test-ch@localhost?database=default/`
but should be
`http://test-ch@localhost?database=default`

test 2
```php
 $rawSql = "select 1";
$url = 'http://test-ch@localhost?database=default';
$client = new Client([
   transport' => 'yii\httpclient\CurlTransport'
]);
 $response =  $client
           ->setUrl($url)
           ->createRequest()
           ->setMethod('POST')
           ->setContent($rawSql)
           ->send();
```
error 
`Query error: Curl error: #3 - <url> malformed`
| Q                       | A
| ----------------------- | ---
| Yii version 2.0.10  |
| Yii HTTP Client version 2.0.0.1 |
| PHP version  7 or 5.6.25RC1           |
| Operating system   Centos or windows7     |

**Comment by klimov-paul** [comment]
Resolved by commit c54d71a59b4071797da877e3fc2d4403d35dc03c

**Comment by sanchezzzhak** [comment]
those changes have not helped.
I have decided here, new class
```
class Request extends \yii\httpclient\Request
{

    public function prepare()
    {
        parent::prepare();
        $this->afterPrepareUrl();

    }

    /**
     * Normalizes [[url]] value, filling it with actual string URL value.
     */
    private function afterPrepareUrl()
    {
        $url = $this->getFullUrl();
        if (strpos($url,'?') !== false) {
            $url = trim($url,'/');
            $this->setUrl($url);
        }
    }

}
```

**Comment by klimov-paul** [comment]
Provide the unit test to reproduce the issue.

**Comment by sanchezzzhak** [comment]
I'm sorry but I have not checked the changes of the dev-master.
dev-master all of works good
