### ISSUE TITLE
Content-Disposition header is invalid

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-httpclient#81]
The code `$request->addContent('inputname', 'somedata', ['contentType' => 'text/plain']);` generates invalid `Content-Disposition` header (due to ";" at the end of the header) which violates the spec and prevents some spec-complaint systems to understand the header.

Example of generated header (incorrect):
```
Content-Disposition: form-data; name="inputname";
```
Correct header:
```
Content-Disposition: form-data; name="inputname"
```

https://tools.ietf.org/html/rfc6266
https://tools.ietf.org/html/rfc7578

**Comment by cebe** [comment]
fixed, thanks for reporting!
