### ISSUE TITLE
Support for domain name on localhost

### ISSUE THREAD

**Issue by michaelnguyen547** [yiisoft/yii2-httpclient#84]
### What steps will reproduce the problem?
modify your hosts file
*erp.ca (there is an existing erp.ca site, but this will point to your Yii app on your dev machine)
*erp.local (this is a non-existing domain name)

```php
$url = "http://erp.local"; // or $url="http://erp.ca"
$client = new \yii\httpclient\Client();
        $response = $client->createRequest()
                ->setMethod('get')
                ->setUrl($url)
                ->send();
```

### What's expected?
I expect local Yii app will serve

### What do you get instead?
For existing domain name, the real website is served instead of my local Yii even though I overwrote the hosts file

For non-existing domain name, Http Client Exception is thrown

HTTP Client Exception - yii\httpclient\Exception
fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.9
| Yii HTTP Client version | 2.0.2
| PHP version             | 5.6
| Operating system        | Ubuntu 14.04

**Comment by klimov-paul** [comment]
This is not Yii issue.
- make sure your web server respects your 'hosts' override.
- try to use `CurlTransport` instead of `StreamTransport`

**Comment by michaelnguyen547** [comment]
Hi @klimov-paul 

I use the CurlTransport as you suggested and get Curl error: #6 - Could not resolve host: erp.local

I think "web server respects hosts override" because when I enter the "hosts" override in a browser (Chrome), my local Yii app is served.

Thanks

**Comment by klimov-paul** [comment]
Can you provide a working code on plain PHP, which will work for your task?

**Comment by michaelnguyen547** [comment]
hi @klimov-paul 

I am using Vagrant Box (https://box.scotch.io/) for development. This box has IP 192.168.33.10. I set up a simple Yii app on Vagrant Box.

On my Host machine (Wins 10), I added 2 new entries to hosts file
* erp.local 192.168.33.10
* erp.ca 192.168.33.10

On my host machine, I can enter erp.local and erp.ca in web browser and both of them will serve the Yii on the Vagrant Box.

To test the Yii2 HttpClient, I use the below

```php
       $client = new \yii\httpclient\Client();
        $response = $client->createRequest()
                ->setMethod('get')
                ->setUrl("http://erp.local")
                ->send();
```
It gives me the error described above. Maybe something is wrong with Vagrant box ?

this is the Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
```

Any recommendations on what I should look for to fix this issue ?

**Comment by cebe** [comment]
> To test the Yii2 HttpClient, I use the below

Does that code run on the VM or on your computer? If inside of the VM you have to configure the hosts there too.

**Comment by DenisAlliswell** [comment]
@cebe that's the key.
