### ISSUE TITLE
avoid high memory usage on big files

### ISSUE THREAD

**Issue by nailfor** [yiisoft/yii2-httpclient#85]
### What steps will reproduce the problem?
$request->addFile('file',$fullFileName);

### What's expected?
It can use all the memory, because
`    public function addFile($name, $fileName, $options = [])
    {
        $content = file_get_contents($fileName);
...
`
loads a file into memory and encodes it
with multiple  upload of even small of files from different users memory has quickly end.

On the other hand сurl can pass the filename and process it on the side of the engine php
For example

`$post = [
	'request' => $data,
];

foreach($_FILES as  $file) {
	if(!isset($post['file'])){
		$post['file'] = [];
	}
	$post['file'][] = "@".$file['tmp_name']; //this string set a filename for upload
}

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $Url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post));`

**Comment by zhukovra** [comment]
Fix typo "avoid hight" -> "Avoid high" in title, please :)

**Comment by acorncom** [comment]
Just ran into the same need when working with JSON files. We're able to work around it for now, but found these two articles that indicate some of the issue:

- https://soyuka.me/streaming-big-json-files-the-good-way/
- https://stackoverflow.com/questions/37887846/php-json-decode-huge-json-file
