### ISSUE TITLE
Crashes on invalid url

### ISSUE THREAD

**Issue by mapexpert** [yiisoft/yii2-httpclient#86]
1. Use streamtransport
2. Use url like   http:/example.com

Expected error thrown

### What do you get instead?
fatal error. try - catch not working also

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |   2.0.11
| Yii HTTP Client version | 2.0.2
| PHP version             |  5.5.19
| Operating system        | windows7

**Comment by klimov-paul** [comment]
There is nothing we can do about this: the fact invalid URL triggers a PHP error is totally expected, while error level is controller by PHP stream library. If you are concern about PHP error instead of exception at this stage - you should report it to php.net

**Comment by mapexpert** [comment]
Thanks Paul
But the error is not in php
Error is thrown while creating response object at StreamTransport.php:73
Because $responseContent is null while array expected

maybe you can add error throwing when $responseContent == null ?

Regards

**Comment by cebe** [comment]
@mapexpert I am unable to reproduce this, I get the following error: `fopen(http:/example.com): failed to open stream: No such file or directory` please show some code to reproduce your issue.

Added a test to verify an exception is thrown: 2a20680

**Comment by mapexpert** [comment]
You have set baseUrl before in setup.
try this:
$image_url = "https:/example.com";
\Yii::$app->http->baseUrl = '';
 $image_data = \Yii::$app->http->get($image_url)->send();
