### ISSUE TITLE
yii\httpclient\Request::addOptions() Problem

### ISSUE THREAD

**Issue by MohammadShafiee** [yiisoft/yii2-httpclient#87]
### What steps will reproduce the problem?

The problem arises from using ArrayHelper::merge
This means that when we add an option like $clientRequest->addOptions([CURLOPT_FOLLOWLOCATION => true]) in this case if CURLOPT_FOLLOWLOCATION that is an integer before exists in the $this->options the repetitive option (CURLOPT_FOLLOWLOCATION) will be added with new integer key that is one greater than the last key of array for example '10083' == CURLOPT_SSL_CIPHER_LIST.
in this case big logical errors may occur.

### What's expected?

as another clear example:

```php
$a = [
            '52' => 1
        ];
        $b = [
            'timeout' => 300,
            '58' => 1,
            '64' => '',
            '10004' => '',
            '59' => 82,
            '10006' => '',
            '52' => 1,
            '10082' => '',
            '10031' => ''
        ];
       $c = \yii\helpers\ArrayHelper::merge($b, $a);
```

in this example $c array will be as follow:

```php
$c = [
            'timeout' => 300,
            '58' => 1,
            '64' => '',
            '10004' => '',
            '59' => 82,
            '10006' => '',
            '52' => 1,
            '10082' => '',
            '10031' => '',
            '10083' => 1
        ];
```
that the last element is incorrect.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2
| Yii HTTP Client version | 2
| PHP version             | >= 5.6
| Operating system        | debian

**Comment by klimov-paul** [comment]
Resolved by commit a0ddfd54b27827aa13dad89933804d730c58d2ec
