### ISSUE TITLE
Duplicating GET params after toString() method

### ISSUE THREAD

**Issue by zvidakovic** [yiisoft/yii2-httpclient#88]
![image](https://cloud.githubusercontent.com/assets/5583862/22755884/686b3ef4-ee45-11e6-9e0b-fbdaabf2d1f0.png)

### What steps will reproduce the problem?
See image. In 4th line, there are duplicate GET params.

### What's expected?
Not duplicate params.

### What do you get instead?
Duplicate params.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.11.1
| Yii HTTP Client version |2.0.2
| PHP version             |5.6
| Operating system        |WIN7

**Comment by klimov-paul** [comment]
Resolved by commit ece52165f2ecb66abb5ac6e0294a7faca6fe63ba
