### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2-httpclient#90]
https://github.com/guzzle/guzzle/issues/1249

**Comment by klimov-paul** [comment]
I can not see any trouble here, since any CURL option, including the ones related to `HTTP 2.0` support can be specified via `Request::$options`, while stream library does not provide a support for `HTTP 2.0` yet.
So what exactly do you require?

**Comment by klimov-paul** [comment]
Closing unless more coherit description provided.
