### ISSUE TITLE
Can not set encodeOptions(default is 0) of JsonFormatter

### ISSUE THREAD

**Issue by yyxx9988** [yiisoft/yii2-httpclient#92]
| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.11
| Yii HTTP Client version | 2.0.3
| PHP version             | 7.0.14
| Operating system        | Linux

**Comment by yyxx9988** [comment]
https://github.com/yiisoft/yii2-httpclient/blob/master/JsonFormatter.php#L25

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-httpclient/blob/master/Client.php#L57-L62
