### ISSUE TITLE
Error 400: Bad Request Cannot parse HTTP request: [GET]

### ISSUE THREAD

**Issue by kategee** [yiisoft/yii2-httpclient#93]
I'm sending a simple get request:

`$client = new Client();
$response = $client->createRequest()->setMethod( 'get' )->setUrl( 'http://localhost:8483/ExecuteOrder?s=INTU&p=117.62&on=ARCA Buy ARCX Limit DAY' )->send();`

It always returns 400 error. It should return xml response which if I go to the URL manually it does return fine. What's weirder is if I change the URL to http://localhost:8483/GetTransactions?user=594929` it works fine. I've also tested the execution in C# so the server only returns 400 using this method. Tried cUrl, various formats but nothing seems to work. I it possible that the spaces are the issue? I tried urlencode and that didn't make a diff.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.11.2
| Yii HTTP Client version | 2.0.0
| PHP version             | PHP/5.6.30
| Operating system        | Apache/2.4.25 (Win64) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by kategee** [comment]
It is the spaces that are causing the issue. I think you guys already encode it but for some reason I have to use `rawurlencode` is there an option to use a different encoding on the data?

**Comment by klimov-paul** [comment]
In case you set request URL as a string you should handle urlencoding yourself.
However you can specify URL as array of parameters - then they will be encoded automatically:

```
$response = $client->createRequest()
     ->setMethod( 'get' )
     ->setUrl([
        'http://localhost:8483/ExecuteOrder'
        's'= >'INTU'
        'p'=>'117.62'
        'on' => 'ARCA Buy ARCX Limit DAY'
     ])
     ->send();
```

You can use `rawurlencode()` specifying `Client::FORMAT_RAW_URLENCODED` as a request format:
https://github.com/yiisoft/yii2-httpclient/blob/master/Client.php#L47
