### ISSUE TITLE
XmlParser not respecting character encoding

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2-httpclient#94]
### What steps will reproduce the problem?

Receiving a http response encoded using something other than UTF-8 (such as EUC-JP, EUC-KR ...).

### What's expected?

XmlParser should take the encoding as declared in the response header into consideration.
This [StackOverflow answer](https://stackoverflow.com/questions/2899274/simplexml-load-string-fail-to-parse-error/2901794#2901794) explains the problem and offers a solution.

### What do you get instead?

```PHP Warning 'yii\base\ErrorException' with message 'simplexml_load_string(): Entity: line 6: parser error : Input is not proper UTF-8, indicate encoding !```

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.11
| Yii HTTP Client version | 2.0.3
| PHP version             | 5.6
| Operating system        | Ubuntu 16.04

**Comment by klimov-paul** [comment]
Resolved by commit 2f3ad950117f65e9b50b54075526033ca23d5b4d
