### ISSUE TITLE
Cookie value should not be urlencoded

### ISSUE THREAD

**Issue by insperedia** [yiisoft/yii2-httpclient#98]
Recently stuck in problem getting  error 500 from server.
Found that problem was caused by urlencode of cookie value (request->composeCookieHeader method).
Cookie was this: JSESSIONID_External_S1=0000SEfsfBVJZgWJAk2LmTiJ4ow:-1
Looks like browser does not do urlencode on cookie values.

**Comment by klimov-paul** [comment]
Resolved by commit f6adc26049281b2c7ba3224015e9a69e676ccde9
