### ISSUE TITLE
Problem when send HEAD request via CurlTransport

### ISSUE THREAD

**Issue by vuongminh** [yiisoft/yii2-httpclient#99]
### What steps will reproduce the problem?
Send head request to download url to get content-length in response headers.

### What's expected?
Get headers of download url

### What do you get instead?
Get both headers and binary content

### Additional info
[CurlTransport.php#L151](https://github.com/yiisoft/yii2-httpclient/blob/master/CurlTransport.php#L151) must be use `empty` to check content because formatter of request will be damaged content when prepare it.

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.11.2
| Yii HTTP Client version | dev-master
| PHP version             | 7.1

**Comment by klimov-paul** [comment]
Resolved by commit 453252591554f5a9286980c1656a5c8a0c25de6c
